window.SANA_DATA = {
  places: [
    {id:'loktak', name:'Loktak Lake', district:'Bishnupur', type:'Lake', tags:['Nature','Culture'], best:['Oct','Nov','Dec','Jan','Feb','Mar'], cost:'Mid-range', distance:48, image:'loktak.jpg', blurb:'A vast freshwater lake dotted with living, floating islands.', tip:'Go near sunrise for quiet water and softer light.'},
    {id:'keibul', name:'Keibul Lamjao National Park', district:'Bishnupur', type:'Wildlife', tags:['Nature','Wildlife'], best:['Nov','Dec','Jan','Feb','Mar'], cost:'Mid-range', distance:53, image:'keibul-lamjao.jpg', blurb:'The floating national park and home of the endangered Sangai deer.', tip:'Book a morning visit and carry binoculars.'},
    {id:'karang', name:'Karang Island', district:'Bishnupur', type:'Island', tags:['Nature','Slow travel'], best:['Oct','Nov','Dec','Jan','Feb','Mar'], cost:'Budget', distance:56, image:'karang.jpg', blurb:'A peaceful island community set in the waters of Loktak.', tip:'Keep the day unhurried; ferries and light change the pace.'},
    {id:'kangla', name:'Kangla Fort', district:'Imphal West', type:'Heritage', tags:['History','Culture'], best:['Jan','Feb','Mar','Oct','Nov','Dec'], cost:'Budget', distance:3, image:'kangla.jpg', blurb:'A layered cultural and historic site in the centre of Imphal.', tip:'Allow time to walk the grounds rather than rushing through.'},
    {id:'ima', name:'Ima Keithel', district:'Imphal West', type:'Market', tags:['Culture','Food'], best:['All year'], cost:'Budget', distance:2, image:'ima-keithel.jpg', blurb:'A landmark market run by women, rich with local produce and craft.', tip:'Ask before photographing stalls and arrive earlier for the best bustle.'},
    {id:'museum', name:'Manipur State Museum', district:'Imphal West', type:'Museum', tags:['History','Culture'], best:['All year'], cost:'Budget', distance:3, image:'state-museum.jpg', blurb:'A compact introduction to the region’s art, archaeology and living traditions.', tip:'Pair it with Kangla Fort for an easy city day.'},
    {id:'govindajee', name:'Shree Govindajee Temple', district:'Imphal East', type:'Temple', tags:['Culture','Architecture'], best:['All year'], cost:'Budget', distance:5, image:'govindajee.jpg', blurb:'A serene white temple known for its distinctive Vaishnavite architecture.', tip:'Dress modestly and visit outside peak prayer times.'},
    {id:'shirui', name:'Shirui Hills', district:'Ukhrul', type:'Trek', tags:['Nature','Trekking'], best:['Apr','May','Jun','Oct','Nov'], cost:'Mid-range', distance:84, image:'shirui.jpg', blurb:'Highland trails and the famed Shirui lily landscape near Ukhrul.', tip:'Conditions shift quickly—bring a warm layer and good shoes.'},
    {id:'ukhrul', name:'Ukhrul', district:'Ukhrul', type:'Hill town', tags:['Nature','Culture'], best:['Mar','Apr','May','Oct','Nov'], cost:'Mid-range', distance:83, image:'ukhrul.jpg', blurb:'A hill town with wide views, Tangkhul Naga culture and cool air.', tip:'Use it as a base for Shirui and nearby viewpoints.'},
    {id:'dzukou', name:'Dzükou Valley', district:'Senapati', type:'Trek', tags:['Nature','Trekking'], best:['Apr','May','Jun','Oct','Nov'], cost:'Budget', distance:120, image:'dzukou.jpg', blurb:'A high valley of seasonal flowers, grasslands and sweeping ridgelines.', tip:'Go with a local guide and check trail conditions before setting out.'},
    {id:'tharon', name:'Tharon Cave', district:'Tamenglong', type:'Cave', tags:['Nature','Adventure'], best:['Oct','Nov','Dec','Jan','Feb','Mar'], cost:'Mid-range', distance:165, image:'tharon-cave.jpg', blurb:'A limestone cave system with long passages and a dramatic setting.', tip:'Wear shoes with grip and confirm local access before travelling.'},
    {id:'tamenglong', name:'Tamenglong', district:'Tamenglong', type:'Hill town', tags:['Nature','Slow travel'], best:['Oct','Nov','Dec','Mar','Apr'], cost:'Budget', distance:150, image:'tamenglong.jpg', blurb:'A quieter mountain district of forests, viewpoints and oranges in season.', tip:'Leave buffer time for the mountain road.'},
    {id:'sadu', name:'Sadu Chiru Waterfall', district:'Kangpokpi', type:'Waterfall', tags:['Nature','Adventure'], best:['Oct','Nov','Dec','Jan','Feb'], cost:'Budget', distance:48, image:'sadu-chiru.jpg', blurb:'A multi-tiered waterfall reached by a short, scenic walk.', tip:'Avoid slippery rocks after heavy rain.'},
    {id:'khonghampat', name:'Khonghampat Orchidarium', district:'Imphal West', type:'Garden', tags:['Nature','Family'], best:['Mar','Apr','May','Jun'], cost:'Budget', distance:11, image:'khonghampat.jpg', blurb:'A small orchid reserve with seasonal colour close to the city.', tip:'Best enjoyed on a dry morning with the rest of Imphal West.'},
    {id:'andro', name:'Andro Heritage Village', district:'Imphal East', type:'Village', tags:['Culture','Food'], best:['All year'], cost:'Budget', distance:25, image:'andro.jpg', blurb:'A village known for pottery, heritage displays and local flavours.', tip:'Look for locally made crafts directly from makers.'},
    {id:'ina', name:'INA Memorial, Moirang', district:'Bishnupur', type:'Memorial', tags:['History','Culture'], best:['All year'], cost:'Budget', distance:45, image:'ina-moirang.jpg', blurb:'A historic memorial that adds context to the Moirang and Loktak area.', tip:'Combine it with Loktak in a single southbound day.'},
    {id:'kakching', name:'Kakching Garden', district:'Kakching', type:'Garden', tags:['Nature','Family'], best:['Oct','Nov','Dec','Jan','Feb'], cost:'Budget', distance:47, image:'kakching-garden.jpg', blurb:'A landscaped hillside garden with open views across the valley.', tip:'Visit late afternoon for gentler light.'},
    {id:'khongjom', name:'Khongjom War Memorial', district:'Thoubal', type:'Memorial', tags:['History','Culture'], best:['All year'], cost:'Budget', distance:35, image:'khongjom.jpg', blurb:'A memorial site commemorating a defining chapter in Manipur’s history.', tip:'Read the interpretive panels for meaningful context.'},
    {id:'bir', name:'Bir Tikendrajit Park', district:'Imphal West', type:'Memorial', tags:['History','Family'], best:['All year'], cost:'Budget', distance:3, image:'birtikendrajit.jpg', blurb:'A city park and memorial space for a quiet pause in Imphal.', tip:'A useful nearby stop between museum and market visits.'},
    {id:'polo', name:'Mapal Kangjeibung', district:'Imphal West', type:'Sports', tags:['History','Culture'], best:['Nov','Dec','Jan','Feb'], cost:'Budget', distance:3, image:'polo-ground.jpg', blurb:'A ground tied to the deep local history of polo, or sagol kangjei.', tip:'Check locally for matches or demonstrations.'}
  ],
  foods: [
    {name:'Eromba', icon:'🌶️', tag:'hot nonveg', desc:'A mashed mix of seasonal vegetables, chilli and fermented fish, usually served with rice.', where:'Local homes & traditional restaurants'},
    {name:'Chamthong', icon:'🥬', tag:'veg', desc:'A light vegetable stew, often finished with fresh herbs and a clean, comforting broth.', where:'Everyday Manipuri kitchens'},
    {name:'Nga Thongba', icon:'🐟', tag:'nonveg hot', desc:'A fragrant fish curry with herbs, vegetables and a gentle warmth.', where:'Imphal & lakeside eateries'},
    {name:'Chak-hao Kheer', icon:'🍚', tag:'veg sweet', desc:'A delicate pudding made from aromatic black rice, milk and sugar.', where:'Sweet shops & home kitchens'},
    {name:'Singju', icon:'🥗', tag:'veg hot', desc:'A bright, crunchy salad of seasonal vegetables, herbs and toasted gram flour.', where:'Market-side snack stalls'},
    {name:'Kabok', icon:'🍘', tag:'veg sweet', desc:'Puffed rice mixed with jaggery or sugar, a simple and much-loved snack.', where:'Local markets'}
  ],
  festivals: [
    {month:'January', name:'Lui-Ngai-Ni', window:'Late January / February', place:'Naga communities across Manipur', desc:'A seed-sowing festival celebrating unity, renewal and cultural performance.'},
    {month:'March', name:'Yaoshang', window:'Five days around Holi', place:'Across Manipur', desc:'A lively spring festival shaped by sport, music and community gatherings.'},
    {month:'April', name:'Cheiraoba', window:'April', place:'Across Manipur', desc:'Manipuri New Year, often observed with family meals and hill climbs.'},
    {month:'November', name:'Sangai Festival', window:'Usually November', place:'Imphal and venues across the state', desc:'A broad cultural festival featuring crafts, food, sport and performances.'},
    {month:'November', name:'Ningol Chakouba', window:'November / December', place:'Across Manipur', desc:'A family-centred festival where married daughters return to their parental homes.'},
    {month:'December', name:'Kang Chingba', window:'Seasonal dates vary', place:'Imphal', desc:'A traditional procession with music, ritual and collective celebration.'}
  ]
};
